### ISSUE TITLE
Not Working: Removing Values from X-Axis and Y-Axis

### ISSUE THREAD

**Issue by DvP17** [deepayan/lattice#13]
The arguments to suppress axis values - `xaxt = "n"` and `yaxt = "n"` - are not working. 

For example in `plot(nlme::Oats, xaxt = "n")`

Best regards and many thanks for your work!

**Comment by deepayan** [comment]
Yes, traditional graphics parameters as documented in `?par` do not apply to lattice (and by extension nlme) plots. Try 

`plot(nlme::Oats, scales = list(x = list(draw = FALSE)))`

**Comment by DvP17** [comment]
Thank you very much!
