### ISSUE TITLE
Title in colorkey

### ISSUE THREAD

**Issue by oscarperpinan** [deepayan/lattice#18]
Hello,

In my package [rasterVis](https://github.com/oscarperpinan/rastervis) I have defined a function for using titles with colorkey. [The function `drawCK`](https://github.com/oscarperpinan/rastervis/blob/master/R/colorkey.R) modifies the grob produced by `lattice::draw.colorkey` adding a text grob with `packGrob`. This solution has been working with previous versions of lattice, but it produces a large triangle with current version 0.20-41 when the legend is located at the right margin.

See the next example:
```
library(rasterVis)

f <- system.file("external/test.grd", package="raster")
r <- raster(f)

levelplot(r, margin = FALSE, colorkey = list(space = "left", title = "[m]"))

levelplot(r, margin = FALSE, colorkey = list(space = "bottom", title = "[m]"))

levelplot(r, margin = FALSE, colorkey = list(space = "right", title = "[m]"))
```
![right](https://user-images.githubusercontent.com/1321370/81505558-6145eb80-92f0-11ea-8a68-e3457d3b17c8.png)

I have revised [this commit](https://github.com/deepayan/lattice/commit/bfb29ec9411edb14c76459c65bc940e6c7885064), where the triangular extensions are implemented. I have checked that `open.upper` is equal to 0 and, consequently, [these lines](https://github.com/deepayan/lattice/blob/f4f809f2c1fec845f99b72f7c7c970099869b422/R/legend.R#L1000-L1011) are not executed. Therefore, I cannot understand why the triangle is created.  Could you give some guidance on this behaviour?

On the other hand, there is already an implementation of title for colorkey in the branch [colorkey-title](https://github.com/deepayan/lattice/tree/colorkey-title), but this feature has not been included in the version 0.20-41. I would be happy to drop the `rasterVis:::drawCK` function and use this lattice feature instead. Do you have plans for including it in the next release?

Thanks in advance for your help.

**Comment by deepayan** [comment]
It seems I have been extremely careless when implementing the triangular ends feature, and only done it for space="right". If I had done it correctly, you would be seeing problems in the other cases as well.

Your approach is fundamentally risky, because it depends on the undocumented internal structure of a frameGrob produced by another package. I would have done it by treating the result of draw.colorkey() as a single grob, but I understand you did it to align the text with the labels. The problem is that you are doing it in row / column = 2, which has changed meaning when two new rows (for space="right") have been added to hold the triangles.

I didn't really get why you couldn't use the first row / column. The following version seems to work with both the old and new structure of the grob produced by draw.colorkey (but it will need testing once I fix the other cases):

```
drawCK <- function(key, space = 'right')
{
    ## Get the grob produced by draw.colorkey
    ck <- draw.colorkey(key)
    ## Define the graphical parameter using the axis.text values as default
    if (is.null(key$title.gpar)) key$title.gpar <- list()
    title.gpar <- modifyList(trellis.par.get("axis.text"), key$title.gpar)
    title.gpar <- do.call(gpar, title.gpar)
    title.grob <-
        switch(space,
               right = textGrob(key$title, x = 0,
                                y = unit(1, 'npc') + unit(0.6, 'lines'),
                                just = 'left', gp = title.gpar),
               left = textGrob(key$title, x = 1,
                               y = unit(1, 'npc') + unit(0.6, 'lines'),
                               just = 'right', gp = title.gpar),
               bottom = textGrob(key$title, y = 0.5,
                                 x = unit(0, 'npc') - unit(0.6, 'lines'),
                                 just = 'right', gp = title.gpar),
               top = textGrob(key$title, y = 0.5,
                              x = unit(0, 'npc') - unit(0.6, 'lines'),
                              just = 'right', gp = title.gpar))
    zw <- unit(0, "mm")
    ck <- switch(space,
                 right = packGrob(ck, title.grob, row = 1, col = 3, height = zw),
                 left = packGrob(ck, title.grob, row = 1, col = 1, height = zw),
                 bottom = packGrob(ck, title.grob, row = 3, col = 1, width = zw),
                 top = packGrob(ck, title.grob, row = 1, col = 1, width = zw))
    ck
}
```

I have been neglecting to review the colorkey-title patch, hopefully I will get to it soon.

**Comment by oscarperpinan** [comment]
Thanks a lot!

> Your approach is fundamentally risky, because it depends on the undocumented internal structure of a frameGrob produced by another package. 

Yes, I agree. :confused:  

> I would have done it by treating the result of draw.colorkey() as a single grob, but I understand you did it to align the text with the labels. The problem is that you are doing it in row / column = 2, which has changed meaning when two new rows (for space="right") have been added to hold the triangles.

Ok, I understand.

> I didn't really get why you couldn't use the first row / column. The following version seems to work with both the old and new structure of the grob produced by draw.colorkey (but it will need testing once I fix the other cases):

Thanks. Do you mind if I use this code in rasterVis?

> I have been neglecting to review the colorkey-title patch, hopefully I will get to it soon.

Good. I will wait for it.

**Comment by deepayan** [comment]
> > I didn't really get why you couldn't use the first row / column. The following version seems to work with both the old and new structure of the grob produced by draw.colorkey (but it will need testing once I fix the other cases):
> 
> Thanks. Do you mind if I use this code in rasterVis?

Of course not, please go ahead.

> > I have been neglecting to review the colorkey-title patch, hopefully I will get to it soon.
> 
> Good. I will wait for it.

It probably won't have support for the corner placement you are doing though, just the four sides.

**Comment by oscarperpinan** [comment]
> I didn't really get why you couldn't use the first row / column. The following version seems to work with both the old and new structure of the grob produced by draw.colorkey (but it will need testing once I fix the other cases).

Checked. It works perfectly. Thanks for your help.
