### ISSUE TITLE
uncatchable error: prettyDate_TMP(x, ...) : range too small for min.n

### ISSUE THREAD

**Issue by jangorecki** [deepayan/lattice#19]
Hi Deepayan,
I produce plots in automated manner and it may sometimes happen that `x` variable is constant. I am fine having an error in that case, but AFAICT bug is that the error is passing through `tryCatch`, which as a results, stops my markdown report rending.
```r
tryCatch(
  xyplot(var~id, data.frame(id=rep(Sys.time(),3),var=1:3)),
  error=function(e) print(e$message)
)
#Error in prettyDate_TMP(x, ...) : range too small for min.n
```
reproducible Linux on R 4.0.3. and a week old R-devel.

**Comment by deepayan** [comment]
This confused me for a while. So what happens is that the tryCatch() returns without any error, and the error actually happens during the subsequent auto-printing:

```r
p <- tryCatch(
  xyplot(var~id, data.frame(id=rep(Sys.time(),3),var=1:3)),
  error=function(e) print(e$message)
)
```

I guess you need the equivalent of

```{r}
tryCatch(print(p), error=function(e) print(e$message))
# [1] "range too small for min.n"
```

**Comment by jangorecki** [comment]
Oh, correct. I should have figure out it was printing error. That would be very weird if error couldn't be caught.
