### ISSUE TITLE
Unexpected behaviour: gridlines cover *some* but not all data points

### ISSUE THREAD

**Issue by NeuKon** [deepayan/lattice#2]
I adopted the solution I found [here](http://grokbase.com/t/r/r-help/06665zmv7g/r-error-bars-in-lattice-xyplot-with-groups) to add error bars to a xyplot with groups. When adding grid lines after using this solution, most data points are being covered despite calling the xyplot function afterwards. Some data points are in front of the grid, as expected. I posted the issue on [stackoverflow](https://stackoverflow.com/questions/44554077/why-do-grid-lines-in-lattice-plot-cover-some-but-not-all-data-points) as well. Even if somebody will suggest a workaround, I would not have expected that behaviour.

`
![rplot](https://user-images.githubusercontent.com/7255874/27153439-5bbec146-5149-11e7-98b1-54859d0b2bd0.png)
library(lattice)

singer.split <- with(singer,
       split(height, voice.part))
singer.ucl <- sapply(singer.split,
         function(x) {
           st <- boxplot.stats(x)
           c(st$stats[3], st$conf)})

singer.ucl <- as.data.frame(t(singer.ucl))
names(singer.ucl) <- c("median", "lower", "upper")
singer.ucl$voice.part <- factor(rownames(singer.ucl),
         levels = rownames(singer.ucl))
singer.ucl$voice=factor(rep(c(1,2),4))
singer.ucl$range=factor(rep(c("Bass","Tenor","Alto","Soprano"),each=2))

prepanel.ci <- function(x, y, ly, uy, subscripts, ...) {
  x <- as.numeric(x)
  ly <- as.numeric(ly[subscripts])
  uy <- as.numeric(uy[subscripts])
  list(ylim = range(y, uy, ly, finite = TRUE))}

panel.ci <- function(x, y, ly, uy, subscripts, pch = 16, col.line =
                       'black', ...) {
  x <- as.numeric(x)
  y <- as.numeric(y)
  ly <- as.numeric(ly[subscripts])
  uy <- as.numeric(uy[subscripts])
  panel.abline(v=1:2, col = "black", lwd = 2)
  panel.arrows(x, ly, x, uy, col = col.line,
               length = 0.25, unit = "native",
               angle = 90, code = 3)
  panel.xyplot(x, y, pch = pch, col.line = col.line, ...)}

xyplot(median ~ voice,
       groups=range,
       data=singer.ucl,
       ly = singer.ucl$lower,
       uy = singer.ucl$upper,
       prepanel = prepanel.ci,
       panel = panel.superpose,
       panel.groups = panel.ci,
       type="p", pch = 19)
`

**Comment by deepayan** [comment]
The panel.abline() call is being repeated for each group, but should actually be called only once before anything else.

````
panel.ci <- function(x, y, ly, uy, subscripts, pch = 16, col.line =
                                                             'black', ...) {
    x <- as.numeric(x)
    y <- as.numeric(y)
    ly <- as.numeric(ly[subscripts])
    uy <- as.numeric(uy[subscripts])
    ## panel.abline(v=1:2, col = "black", lwd = 2)
    panel.arrows(x, ly, x, uy, col = col.line,
                 length = 0.25, unit = "native",
                 angle = 90, code = 3)
    panel.xyplot(x, y, pch = pch, col.line = col.line, ...)
}

xyplot(median ~ voice,
       groups=range,
       data=singer.ucl,
       ly = singer.ucl$lower,
       uy = singer.ucl$upper,
       prepanel = prepanel.ci,
       panel = function(...) {
           panel.abline(v=1:2, col = "black", lwd = 2)
           panel.superpose(...)
       },
       panel.groups = panel.ci,
       type="p", pch = 19)
````

**Comment by NeuKon** [comment]
Thank you very much. This solution is much better than the solution provided at stackoverflow.
