### ISSUE TITLE
base_family and base_size needed

### ISSUE THREAD

**Issue by kongdd** [deepayan/lattice#21]
Currently, it is hard to set font in lattice.
Whether is it possible to add a theme function to control the `base_family` and `base_size`, just like theme_grey function in ggplot2.

I am a big funs of lattice. ggplot is simple. But lattice is more beautiful. Hope lattice could be more simple to use.

**Comment by deepayan** [comment]
Could you give a little more detail on what you want? We can already do

```r
trellis.par.set(grid.pars = list(fontfamily = "Zapfino"), fontsize = list(text = 20))
splom(iris[1:4], groups = iris[[5]], grid = TRUE, auto.key = list(space = "right"))
```
to get 

![iris](https://user-images.githubusercontent.com/423700/116880824-154a3000-ac40-11eb-9b8d-33951cb2da93.png)

**Comment by kongdd** [comment]
I didn't realized lattice can set theme in this way. Thank you.
