### ISSUE TITLE
Probable bug in panel.abline

### ISSUE THREAD

**Issue by sbihorel** [deepayan/lattice#8]
Please, consider the following code

```
require(lattice)

a <- runif(1,0,100)
data <- data.frame(x=c(0,a^2), y=c(0,a^2))

xyplot(
  y~x,
  data = data,
  type = 'l',
  panel = function(x,y,...){
    panel.xyplot(x,y,...)
    panel.abline(c(a^2,-1.0), col=2)
  }
)
```

The abline is not drawn for some reason. Adding noise (eg panel.abline(c(a^2+0.01,-1.0), col=2)) or adding some axis limits seems to bypass the problem.

This happens for data source and abline coefficients:
data <- data.frame(x=c(18,81), y=c(18,81))
...
panel.abline(c(99,-1.0), col=2)

**Comment by pmur002** [comment]
Looks like a problem in the panel.abline() code that determines which edges to draw the line between.  If I debug this, I get A, B, and C (internal variables in panel.abline()) all TRUE, which matches three of the subsequent tests for which edges to draw between.  The first match (A && B) just draws a dot rather than a line (x0==x1 and y0==y1).  I think the problem is basically that the code cannot handle the case where the line hits right in the corner (so intersects more than just two edges).

**Comment by sbihorel** [comment]
Thanks Paul for your post.
I figure it was something along those lines. Interestingly, the problem seems to be specific to the case where the line hits the upper left and/or lower right corner, as the mirror case does not cause any trouble

```
require(lattice)

a <- runif(1,0,100)
data <- data.frame(x=c(0,a^2), y=c(a^2,0))

xyplot(
  y~x,
  data = data,
  type = 'l',
  panel = function(x,y,...){
    panel.xyplot(x,y,...)
    panel.abline(c(0,1.0), col=2)
  }
)
```

**Comment by sbihorel** [comment]
Also, no problem when only the upper left corner or only the bottom right corner is hit
```
require(lattice)

a <- runif(1,0,100)
data <- data.frame(x=c(0,a), y=c(0,a))

xyplot(
  y~x,
  data = data,
  type = 'l',
  panel = function(x,y,...){
    panel.xyplot(x,y,...)
    panel.abline(c(a*(1.0.7 - 0.5*0.07),-0.5), col=2)
  }
)

xyplot(
  y~x,
  data = data,
  type = 'l',
  panel = function(x,y,...){
    panel.xyplot(x,y,...)
    panel.abline(c(a*(0.5*1.07-0.07),-0.5), col=2)
  }
)
```

**Comment by deepayan** [comment]
Sorry for the silence (was traveling). I will have a look.

**Comment by deepayan** [comment]
A,B,C,D should all be TRUE in the diagonal cases; I added a zapsmall() to ensure that.

More importantly, I reordered the cases so that opposite sides (A&&C and B&&D) are handled before adjacent sides. Hopefully this fixes the problem. Let me know if you still spot any problems.
