### ISSUE TITLE
NA values crash barchart calls

### ISSUE THREAD

**Issue by sbihorel** [deepayan/lattice#9]
Hi,

Consider the following calls:
```
require(lattice)
data <- data.frame(
  x = factor(rep(1:3,each=2),
  y = c(10,NA,5,30,10,20),
  z= rep(1:2,each=3)
)
data
barchart(y~x, data = data, groups = z, stack = FALSE) # works fine
barchart(y~x, data = data, groups = z, stack = TRUE) # crashes with or without groups

```

The error is due to the evaluation of "if (any(y<0))" in prepanel.default.bwplot. There seems to be multiple if statements in this function that are not protected against NA values.

A simple data cleanup is the best workaround right now, but I wonder if adding na.rm=TRUE in the any calls would be a good or a bad idea (I am not completely sure of the ramifications).

**Comment by deepayan** [comment]
Finally fixed.
